name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Read .env
        run: cat .env >> $GITHUB_ENV

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '${{ env.HUGO_VERSION }}'
          extended: true

      - name: Build
        run: hugo

      - name: Upload build result
        uses: actions/upload-artifact@v3
        with:
          name: hugo-build-result
          path: public/
